export const reviews = {
  "네팔 친구들은 세금을 돌려받을 수 있다는 사실조차 몰랐어요. 저도 긴가민가하면서 시작했는데 300만원 행운을 얻었습니다! 인증 과정이 조금 힘들 수 있지만 자세히 설명된 대로만 하면 저 같은 외국인도 충분히 성공할 수 있어요.": "My Nepali friends didn't even know they could get a tax refund. I started with doubt, but ended up with a lucky 3 million won! The verification process can be a bit challenging, but if you follow the detailed instructions, even a foreigner like me can definitely succeed.",
  "맨 처음에는 한국어를 몰라서 인증앱을 어떻게 깔아야 하나 걱정부터 앞섰어요. 그런데 이지텍스리펀드의 자세한 안내를 하나하나 따라하다 보니 인증에 성공했구요. 결과는 대박! 제가 받을 수 있는 금액이 310만원이나 되더라구요. 신청 후 2달 뒤에 어김없이 국세청에서 입금되었습니다. 여러분 두려워 마세요!": "At first, I didn't know Korean and was worried about how to install the verification app. But following Easy Tax Refund's detailed step-by-step guide, I succeeded in verification. The result was amazing! My refund amount was 3.1 million won. Exactly two months after applying, the NTS deposited it without fail. Everyone, don't be afraid!",
  "미얀마 친구들이 사기 아니냐고 걱정했는데 제가 먼저 받고 증명했습니다! 115만원 통장에 찍히는 순간 다들 놀랐죠. 인증이 막힌다면 AI 비서에게 물어보세요. 정말 친절하게 알려줍니다. 모두 꼭 해보세요!": "My Myanmar friends were worried it might be a scam, but I received it first and proved them wrong! Everyone was shocked when 1.15 million won hit my account. If you're stuck on verification, just ask the AI assistant. They're very kind. Everyone should try it!",
  "보안이 제일 중요했는데 이 앱은 보안 보증서까지 있어서 안심하고 사용했습니다. 카카오톡 인증 방법이 상세해서 외국인인 저도 5분 만에 끝냈어요. 168만원 환급금 받고 고향 부모님께 선물 보냈습니다. 정말 감사합니다!": "Security was my top priority, and I used it with peace of mind because this app even has a security guarantee. The KakaoTalk verification method was so detailed that even as a foreigner, I finished in 5 minutes. After receiving a 1.68 million won refund, I sent gifts to my parents back home. Thank you so much!",
  "솔직히 처음엔 사기인 줄 알고 의심했어요. 하지만 국세청 공식 데이터를 안전하게 가져온다는 설명을 보고 용기를 냈죠. PASS 앱 인증이 조금 복잡했지만 그림 가이드 덕분에 성공했고, 정확히 8주 뒤에 225만원이 통장으로 들어왔습니다. 정말 믿을 수 있는 서비스예요.": "Honestly, I doubted and thought it was a scam at first. But seeing the explanation that it safely retrieves official NTS data gave me courage. The PASS app verification was a bit complex, but I succeeded thanks to the visual guide, and exactly 8 weeks later, 2.25 million won entered my account. It's a truly reliable service.",
  "신청하고 나서 정말 돈이 들어올까 매일 확인했어요. 정확히 약속한 날짜에 국세청에서 입금 알림이 왔을 때 소리를 질렀습니다! 212만원 환급 성공! 인증앱 때문에 포기하지 마세요. 차근차근 따라하다 보면 행운이 올 거예요.": "After applying, I checked every day to see if the money would really come. When I got the deposit notification from the NTS exactly on the promised date, I screamed with joy! Success with a 2.12 million won refund! Don't give up because of the verification app. If you follow along step-by-step, luck will find you.",
  "이름 대소문자랑 띄어쓰기 때문에 항상 실패했는데, 여기서 알려준 대로 하니까 바로 통과됐어요! 한국어가 서툴러도 그림만 보면 누구나 할 수 있습니다. 185만원이라는 큰 돈이 생겨서 너무 행복합니다. 우즈벡 친구들에게도 다 추천하고 있어요.": "I always failed because of name capitalization and spacing, but following the advice here, I passed immediately! Even if your Korean is poor, anyone can do it just by looking at the pictures. I'm so happy to have a large sum of 1.85 million won. I'm recommending it to all my Uzbek friends.",
  "이미 많은 외국인 동료들이 권리를 찾았습니다": "Many foreign colleagues have already claimed their rights.",
  "인증앱 설치가 외국인에겐 제일 큰 장벽인데, 이 앱은 그걸 아주 쉽게 풀어서 알려줍니다. 보안도 확실해서 개인정보 유출 걱정도 없었어요. 한 달 반 만에 278만원 환급받았습니다. 포기하지 마시고 꼭 도전해 보세요!": "Installing the verification app is the biggest barrier for foreigners, but this app makes it very easy to understand. The security is solid, so I wasn't worried about privacy leaks. I received 2.78 million won back in a month and a half. Don't give up and definitely give it a try!",
  "처음엔 내 정보를 넣는 게 무서웠어요. 하지만 암호화 기술과 무저장 원칙을 보고 신뢰가 생겼습니다. 인증 성공하고 조회해보니 142만원이나 있었네요! 실제로 돈이 입금되는 걸 확인하니 정말 감격스러웠습니다. 이지텍스리펀드 팀 감사합니다.": "At first, I was scared to put in my info. But seeing the encryption technology and the non-storage principle gave me trust. After successful verification, I found I had 1.42 million won! I was truly moved when I saw the actual deposit. Thank you, Easy Tax Refund team.",
  "통신사 인증이 항상 문제였는데, 여기서 알려준 팁 덕분에 드디어 해결했습니다. 소액이라고 생각했는데 95만원이나 들어오니 기분 최고네요! 외국인을 위한 이런 서비스가 있어서 정말 다행입니다. 여러분도 본인의 권리를 찾으세요.": "Carrier verification was always a problem, but I finally solved it thanks to the tips here. I thought it would be a small amount, but getting 950,000 won feels great! I'm so glad there's a service like this for foreigners. Everyone, go claim your own rights.",
  "함께하는 동료들의 리얼 후기": "Real Reviews from Fellow Colleagues",
};
