export const reviews = {
  "네팔 친구들은 세금을 돌려받을 수 있다는 사실조차 몰랐어요. 저도 긴가민가하면서 시작했는데 300만원 행운을 얻었습니다! 인증 과정이 조금 힘들 수 있지만 자세히 설명된 대로만 하면 저 같은 외국인도 충분히 성공할 수 있어요.": "Nepal do'stlarim soliqni qaytarish mumkinligini bilishmas edi. Men ham shubha bilan boshladim, lekin 3 million vonlik omadga erishdim! Identifikatsiya jarayoni biroz qiyin bo'lishi mumkin, lekin tushuntirilganidek qilsangiz, men kabi chet elliklar ham muvaffaqiyatga erishishi mumkin.",
  "맨 처음에는 한국어를 몰라서 인증앱을 어떻게 깔아야 하나 걱정부터 앞섰어요. 그런데 이지텍스리펀드의 자세한 안내를 하나하나 따라하다 보니 인증에 성공했구요. 결과는 대박! 제가 받을 수 있는 금액이 310만원이나 되더라구요. 신청 후 2달 뒤에 어김없이 국세청에서 입금되었습니다. 여러분 두려워 마세요!": "Koreys tilini bilmaganim uchun identifikatsiya ilovasini qanday o'rnatish haqida juda xavotirda edim. Lekin Easy Tax Refund qo'llanmalarini birma-bir bajarib, muvaffaqiyatga erishdim. Natija esa ajoyib! Men 3,1 million von olishim mumkin ekan. 2 oydan so'ng pul hisobimga tushdi. Qo'rqmanglar!",
  "미얀마 친구들이 사기 아니냐고 걱정했는데 제가 먼저 받고 증명했습니다! 115만원 통장에 찍히는 순간 다들 놀랐죠. 인증이 막힌다면 AI 비서에게 물어보세요. 정말 친절하게 알려줍니다. 모두 꼭 해보세요!": "Myanmalik do'stlarim bu aldoqchilik bo'lsa-chi deb xavotir olishdi, lekin men pulni olganimni ko'rib hammasi ishonishdi! 1,15 million von hisobimga tushganida hamma hayron qoldi. Agar qiynalsangiz, AI yordamchisidan so'rang, u juda yaxshi tushuntiradi. Sinab ko'ring!",
  "보안이 제일 중요했는데 이 앱은 보안 보증서까지 있어서 안심하고 사용했습니다. 카카오톡 인증 방법이 상세해서 외국인인 저도 5분 만에 끝냈어요. 168만원 환급금 받고 고향 부모님께 선물 보냈습니다. 정말 감사합니다!": "Xavfsizlik eng muhimi edi va men bunga ishondim. KakaoTalk orqali tasdiqlash juda oson ekan. 1.68 million von olib, ota-onamga sovg'a yubordim. Rahmat!",
  "솔직히 처음엔 사기인 줄 알고 의심했어요. 하지만 국세청 공식 데이터를 안전하게 가져온다는 설명을 보고 용기를 냈죠. PASS 앱 인증이 조금 복잡했지만 그림 가이드 덕분에 성공했고, 정확히 8주 뒤에 225만원이 통장으로 들어왔습니다. 정말 믿을 수 있는 서비스예요.": "Rostini aytsam, boshida bu firibgarlik deb o'yladim. Lekin soliq idorasining rasmiy ma'lumotlar bilan ishlashini bilgach, sinab ko'rishga qaror qildim. PASS ilovasi biroz murakkab bo'lsa-da, rasmli qo'llanmalar bilan barchasini uddaladim. 8 haftadan so'ng 2,25 million von tushdi. Juda ishonchli xizmat!",
  "신청하고 나서 정말 돈이 들어올까 매일 확인했어요. 정확히 약속한 날짜에 국세청에서 입금 알림이 왔을 때 소리를 질렀습니다! 212만원 환급 성공! 인증앱 때문에 포기하지 마세요. 차근차근 따라하다 보면 행운이 올 거예요.": "Ariza topshirgach, pul tushadimi deb har kuni xavotir bilan tekshirdim. Va'da qilingan kuni soliq idorasidan SMS kelganida shodligimdan baqirib yubordim! 2,12 million von! Ilovadagi qiyinchiliklar sabab taslim bo'lmang, qo'llanmalarni birma-bir bajarsangiz, omad sizga ham kulib boqadi.",
  "이름 대소문자랑 띄어쓰기 때문에 항상 실패했는데, 여기서 알려준 대로 하니까 바로 통과됐어요! 한국어가 서툴러도 그림만 보면 누구나 할 수 있습니다. 185만원이라는 큰 돈이 생겨서 너무 행복합니다. 우즈벡 친구들에게도 다 추천하고 있어요.": "Ism yozishda doim xato qilardim, lekin bu yerdagi maslahatlar yordam berdi! Koreys tilini yaxshi bilmasangiz ham rasmlar orqali tushunasiz. 1.85 million von oldim. O'zbek do'stlarimga tavsiya qilyapman.",
  "이미 많은 외국인 동료들이 권리를 찾았습니다": "Ko'plab chet ellik hamyurtlarimiz o'z huquqlarini tikladilar",
  "인증앱 설치가 외국인에겐 제일 큰 장벽인데, 이 앱은 그걸 아주 쉽게 풀어서 알려줍니다. 보안도 확실해서 개인정보 유출 걱정도 없었어요. 한 달 반 만에 278만원 환급받았습니다. 포기하지 마시고 꼭 도전해 보세요!": "Identifikatsiya ilovasini o'rnatish chet elliklar uchun eng katta to'siq, lekin bu ilova uni juda oson tushuntirib beradi. Xavfsizlik yuqori darajada ekani ishonch berdi. Bir yarim oy ichida 2,78 million von oldim. Hech ham ikkilanmang!",
  "처음엔 내 정보를 넣는 게 무서웠어요. 하지만 암호화 기술과 무저장 원칙을 보고 신뢰가 생겼습니다. 인증 성공하고 조회해보니 142만원이나 있었네요! 실제로 돈이 입금되는 걸 확인하니 정말 감격스러웠습니다. 이지텍스리펀드 팀 감사합니다.": "Shaxsiy ma'lumotlarimni kiritishdan boshida qo'rqdim. Lekin shifrlash texnologiyasi va ma'lumotlarni saqlamaslik tamoyilini ko'rib, ishonchim ortdi. 1,42 million von pulim borligini bilganimda va keyin u haqiqatan ham tushganida juda xursand bo'ldim. Rahmat!",
  "통신사 인증이 항상 문제였는데, 여기서 알려준 팁 덕분에 드디어 해결했습니다. 소액이라고 생각했는데 95만원이나 들어오니 기분 최고네요! 외국인을 위한 이런 서비스가 있어서 정말 다행입니다. 여러분도 본인의 권리를 찾으세요.": "Tasdiqlash doim muammo edi, lekin bu yerdagi maslahatlar bilan hal qildim. 950 ming von oldim! Chet elliklar uchun shunday xizmat borligidan xursandman.",
  "함께하는 동료들의 리얼 후기": "Hamkasblarimizning samimiy fikrlari",
};
