export const reviews = {
  "네팔 친구들은 세금을 돌려받을 수 있다는 사실조차 몰랐어요. 저도 긴가민가하면서 시작했는데 300만원 행운을 얻었습니다! 인증 과정이 조금 힘들 수 있지만 자세히 설명된 대로만 하면 저 같은 외국인도 충분히 성공할 수 있어요.": "Teman-teman dari Nepal bahkan tidak tahu bahwa mereka bisa mendapatkan pajak mereka kembali. Saya pun mulai dengan ragu, tapi akhirnya beruntung mendapatkan 3 juta won! Proses verifikasinya mungkin sedikit sulit, tapi jika Anda mengikuti penjelasan detailnya, orang asing seperti saya pun pasti bisa berhasil.",
  "맨 처음에는 한국어를 몰라서 인증앱을 어떻게 깔아야 하나 걱정부터 앞섰어요. 그런데 이지텍스리펀드의 자세한 안내를 하나하나 따라하다 보니 인증에 성공했구요. 결과는 대박! 제가 받을 수 있는 금액이 310만원이나 되더라구요. 신청 후 2달 뒤에 어김없이 국세청에서 입금되었습니다. 여러분 두려워 마세요!": "Awalnya saya khawatir karena tidak tahu bahasa Korea dan bingung cara menginstal aplikasi verifikasi. Namun, setelah mengikuti panduan detail dari Easy Tax Refund satu per satu, saya berhasil melakukan verifikasi. Hasilnya luar biasa! Jumlah yang bisa saya terima mencapai 3,1 juta won. Dua bulan setelah pengajuan, uang itu benar-benar disetor ke rekening oleh kantor pajak. Teman-teman, jangan takut!",
  "미얀마 친구들이 사기 아니냐고 걱정했는데 제가 먼저 받고 증명했습니다! 115만원 통장에 찍히는 순간 다들 놀랐죠. 인증이 막힌다면 AI 비서에게 물어보세요. 정말 친절하게 알려줍니다. 모두 꼭 해보세요!": "Teman-teman dari Myanmar khawatir ini penipuan, tapi saya membuktikannya setelah menerimanya lebih dulu! Semua orang terkejut saat melihat 1,15 juta won masuk ke tabungan saya. Jika proses verifikasi terhambat, tanyakan pada asisten AI. Mereka menjelaskannya dengan sangat ramah. Semua harus mencobanya!",
  "보안이 제일 중요했는데 이 앱은 보안 보증서까지 있어서 안심하고 사용했습니다. 카카오톡 인증 방법이 상세해서 외국인인 저도 5분 만에 끝냈어요. 168만원 환급금 받고 고향 부모님께 선물 보냈습니다. 정말 감사합니다!": "Keamanan adalah yang terpenting bagi saya, dan aplikasi ini memiliki sertifikat jaminan keamanan sehingga saya tenang menggunakannya. Cara verifikasi KakaoTalk sangat detail, jadi saya yang orang asing pun bisa menyelesaikannya dalam 5 menit. Setelah menerima pengembalian 1,68 juta won, saya mengirim hadiah untuk orang tua di kampung halaman. Terima kasih banyak!",
  "솔직히 처음엔 사기인 줄 알고 의심했어요. 하지만 국세청 공식 데이터를 안전하게 가져온다는 설명을 보고 용기를 냈죠. PASS 앱 인증이 조금 복잡했지만 그림 가이드 덕분에 성공했고, 정확히 8주 뒤에 225만원이 통장으로 들어왔습니다. 정말 믿을 수 있는 서비스예요.": "Jujur, awalnya saya curiga dan mengira ini penipuan. Namun, setelah melihat penjelasan bahwa data resmi NTS diambil dengan aman, saya memberanikan diri. Verifikasi aplikasi PASS agak rumit, tapi berkat panduan gambar saya berhasil, dan tepat 8 minggu kemudian 2,25 juta won masuk ke rekening. Ini adalah layanan yang benar-benar bisa dipercaya.",
  "신청하고 나서 정말 돈이 들어올까 매일 확인했어요. 정확히 약속한 날짜에 국세청에서 입금 알림이 왔을 때 소리를 질렀습니다! 212만원 환급 성공! 인증앱 때문에 포기하지 마세요. 차근차근 따라하다 보면 행운이 올 거예요.": "Setelah mengajukan, saya mengecek setiap hari apakah uangnya akan benar-benar masuk. Saya berteriak kegirangan saat notifikasi setoran dari kantor pajak datang tepat pada tanggal yang dijanjikan! Berhasil mendapatkan 2,12 juta won! Jangan menyerah karena aplikasi verifikasi. Jika Anda mengikutinya perlahan-lahan, keberuntungan akan datang.",
  "이름 대소문자랑 띄어쓰기 때문에 항상 실패했는데, 여기서 알려준 대로 하니까 바로 통과됐어요! 한국어가 서툴러도 그림만 보면 누구나 할 수 있습니다. 185만원이라는 큰 돈이 생겨서 너무 행복합니다. 우즈벡 친구들에게도 다 추천하고 있어요.": "Saya selalu gagal karena masalah huruf besar/kecil dan spasi pada nama, tapi setelah melakukan apa yang diarahkan di sini, langsung lolos! Meskipun bahasa Korea saya kurang lancar, siapa pun bisa melakukannya hanya dengan melihat gambar. Saya sangat bahagia mendapatkan uang besar sebanyak 1,85 juta won. Saya merekomendasikannya kepada semua teman di Uzbekistan.",
  "이미 많은 외국인 동료들이 권리를 찾았습니다": "Sudah banyak rekan kerja asing yang telah menemukan hak mereka",
  "인증앱 설치가 외국인에겐 제일 큰 장벽인데, 이 앱은 그걸 아주 쉽게 풀어서 알려줍니다. 보안도 확실해서 개인정보 유출 걱정도 없었어요. 한 달 반 만에 278만원 환급받았습니다. 포기하지 마시고 꼭 도전해 보세요!": "Instalasi aplikasi verifikasi adalah hambatan terbesar bagi warga asing, tapi aplikasi ini menjelaskannya dengan sangat mudah. Keamanannya juga terjamin sehingga saya tidak khawatir tentang kebocoran informasi pribadi. Saya menerima pengembalian 2,78 juta won dalam waktu satu setengah bulan. Jangan menyerah dan pastikan untuk mencoba!",
  "처음엔 내 정보를 넣는 게 무서웠어요. 하지만 암호화 기술과 무저장 원칙을 보고 신뢰가 생겼습니다. 인증 성공하고 조회해보니 142만원이나 있었네요! 실제로 돈이 입금되는 걸 확인하니 정말 감격스러웠습니다. 이지택스리펀드 팀 감사합니다.": "Awalnya saya takut memasukkan informasi saya. Namun, setelah melihat teknologi enkripsi dan prinsip tanpa penyimpanan, saya menjadi percaya. Setelah verifikasi berhasil dan dicek, ternyata ada 1,42 juta won! Saya sangat terharu saat melihat uang itu benar-benar disetor. Terima kasih tim Easy Tax Refund.",
  "통신사 인증이 항상 문제였는데, 여기서 알려준 팁 덕분에 드디어 해결했습니다. 소액이라고 생각했는데 95만원이나 들어오니 기분 최고네요! 외국인을 위한 이런 서비스가 있어서 정말 다행입니다. 여러분도 본인의 권리를 찾으세요.": "Verifikasi operator seluler selalu menjadi masalah, tapi berkat tips yang diberikan di sini, akhirnya teratasi. Saya pikir jumlahnya kecil, tapi ternyata 950 ribu won masuk, perasaan saya sangat senang! Beruntung sekali ada layanan seperti ini untuk warga asing. Teman-teman, temukan juga hak Anda sendiri.",
  "함께하는 동료들의 리얼 후기": "Ulasan Nyata dari Rekan-rekan yang Bergabung",
};
