export const reviews = {
  "네팔 친구들은 세금을 돌려받을 수 있다는 사실조차 몰랐어요. 저도 긴가민가하면서 시작했는데 300만원 행운을 얻었습니다! 인증 과정이 조금 힘들 수 있지만 자세히 설명된 대로만 하면 저 같은 외국인도 충분히 성공할 수 있어요.": "Bạn bè người Nepal của tôi thậm chí còn không biết là có thể lấy lại tiền thuế. Tôi cũng bắt đầu with tâm thế nửa tin nửa ngờ nhưng đã may mắn nhận được 3 triệu won! Quy trình xác thực có thể hơi khó khăn nhưng nếu làm đúng theo hướng dẫn chi tiết, người nước ngoài như tôi hoàn toàn có thể thành công.",
  "맨 처음에는 한국어를 몰라서 인증앱을 어떻게 깔아야 하나 걱정부터 앞섰어요. 그런데 이지텍스리펀드의 자세한 안내를 하나하나 따라하다 보니 인증에 성공했구요. 결과는 대박! 제가 받을 수 있는 금액이 310만원이나 되더라구요. 신청 후 2달 뒤에 어김없이 국세청에서 입금되었습니다. 여러분 두려워 마세요!": "Lúc đầu tôi lo lắng vì không biết tiếng Hàn nên không biết cài ứng dụng xác thực thế nào. Nhưng nhờ làm theo hướng dẫn chi tiết của Easy Tax Refund từng bước một mà tôi đã xác thực thành công. Kết quả thật bất ngờ! Tôi được hoàn lại tới 3,1 triệu won. Sau 2 tháng, tiền đã được Cơ quan Thuế gửi vào tài khoản. Mọi người đừng lo lắng nhé!",
  "미얀마 친구들이 사기 아니냐고 걱정했는데 제가 먼저 받고 증명했습니다! 115만원 통장에 찍히는 순간 다들 놀랐죠. 인증이 막힌다면 AI 비서에게 물어보세요. 정말 친절하게 알려줍니다. 모두 꼭 해보세요!": "Các bạn người Myanmar lo lắng đây là lừa đảo nhưng tôi đã nhận được tiền trước và chứng minh! Khoảnh khắc 1,15 triệu won hiện lên, ai cũng ngạc nhiên. Nếu việc xác thực bị kẹt, hãy hỏi trợ lý AI. Nó sẽ hướng dẫn rất tận tình. Mọi người hãy thử nhé!",
  "보안이 제일 중요했는데 이 앱은 보안 보증서까지 있어서 안심하고 사용했습니다. 카카오톡 인증 방법이 상세해서 외국인인 저도 5분 만에 끝냈어요. 168만원 환급금 받고 고향 부모님께 선물 보냈습니다. 정말 감사합니다!": "Bảo mật là quan trọng nhất và ứng dụng này có cả chứng nhận bảo mật nên tôi rất yên tâm sử dụng. Cách xác thực KakaoTalk rất chi tiết nên người nước ngoài như tôi cũng chỉ mất 5 phút là xong. Tôi đã nhận được 1,68 triệu won và gửi quà về cho bố mẹ ở quê. Cảm ơn rất nhiều!",
  "솔직히 처음엔 사기인 줄 알고 의심했어요. 하지만 국세청 공식 데이터를 안전하게 가져온다는 설명을 보고 용기를 냈죠. PASS 앱 인증이 조금 복잡했지만 그림 가이드 덕분에 성공했고, 정확히 8주 뒤에 225만원이 통장으로 들어왔습니다. 정말 믿을 수 있는 서비스예요.": "Thú thực lúc đầu tôi cũng nghi ngờ tưởng là lừa đảo. Nhưng sau khi xem giải thích về việc lấy dữ liệu an toàn từ Cơ quan Thuế, tôi đã can đảm hơn. Xác thực ứng dụng PASS hơi phức tạp nhưng nhờ hướng dẫn bằng hình ảnh mà tôi đã thành công, và đúng 8 tuần sau 2,25 triệu won đã được gửi vào tài khoản. Đây là một dịch vụ rất đáng tin cậy. Cảm ơn rất nhiều!",
  "신청하고 나서 정말 돈이 들어올까 매일 확인했어요. 정확히 약속한 날짜에 국세청에서 입금 알림이 왔을 때 소리를 질렀습니다! 212만원 환급 성공! 인증앱 때문에 포기하지 마세요. 차근차근 따라하다 보면 행운이 올 거예요.": "Sau khi đăng ký, tôi kiểm tra mỗi ngày xem tiền có thực sự về không. Khi nhận được thông báo tiền về từ Cơ quan Thuế đúng ngày đã hẹn, tôi đã hét lên sung sướng! Hoàn thuế 2,12 triệu won thành công! Đừng bỏ cuộc vì ứng dụng xác thực. Nếu làm theo từng bước, vận may sẽ đến với bạn.",
  "이름 대소문자랑 띄어쓰기 때문에 항상 실패했는데, 여기서 알려준 대로 하니까 바로 통과됐어요! 한국어가 서툴러도 그림만 보면 누구나 할 수 있습니다. 185만원이라는 큰 돈이 생겨서 너무 행복합니다. 우즈벡 친구들에게도 다 추천하고 있어요.": "Tôi luôn thất bại vì lỗi chữ hoa chữ thường và khoảng trắng trong tên, nhưng làm theo cách ở đây chỉ dạy là tôi đã vượt qua ngay! Dù tiếng Hàn không giỏi, chỉ cần nhìn hình ảnh là ai cũng làm được. Tôi rất hạnh phúc khi nhận được số tiền lớn 1,85 triệu won. Tôi đang giới thiệu cho tất cả bạn bè người Uzbekistan của mình.",
  "이미 많은 외국인 동료들이 권리를 찾았습니다": "Nhiều người nước ngoài đã tìm lại được quyền lợi của mình.",
  "인증앱 설치가 외국인에겐 제일 큰 장벽인데, 이 앱은 그걸 아주 쉽게 풀어서 알려줍니다. 보안도 확실해서 개인정보 유출 걱정도 없었어요. 한 달 반 만에 278만원 환급받았습니다. 포기하지 마시고 꼭 도전해 보세요!": "Cài đặt ứng dụng xác thực là rào cản lớn nhất với người nước ngoài, nhưng ứng dụng này đã giải thích rất dễ hiểu. Bảo mật cũng rất chắc chắn nên tôi không lo bị lộ thông tin cá nhân. Sau một tháng rưỡi, tôi đã nhận được 2,78 triệu won tiền hoàn lại. Đừng bỏ cuộc và hãy thử xem sao!",
  "처음엔 내 정보를 넣는 게 무서웠어요. 하지만 암호화 기술과 무저장 원칙을 보고 신뢰가 생겼습니다. 인증 성공하고 조회해보니 142만원이나 있었네요! 실제로 돈이 입금되는 걸 확인하니 정말 감격스러웠습니다. 이지텍스리펀드 팀 감사합니다.": "Lúc đầu tôi sợ khi phải nhập thông tin của mình. Nhưng sau khi thấy công nghệ mã hóa và nguyên tắc không lưu trữ, tôi đã tin tưởng. Sau khi xác thực thành công và tra cứu, tôi thấy mình có tới 1,42 triệu won! Tôi thực sự xúc động khi thấy tiền được gửi vào tài khoản. Cảm ơn đội ngũ Easy Tax Refund.",
  "통신사 인증이 항상 문제였는데, 여기서 알려준 팁 덕분에 드디어 해결했습니다. 소액이라고 생각했는데 95만원이나 들어오니 기분 최고네요! 외국인을 위한 이런 서비스가 있어서 정말 다행입니다. 여러분도 본인의 권리를 찾으세요.": "Xác thực nhà mạng luôn là vấn đề, nhưng nhờ mẹo ở đây mà cuối cùng tôi đã giải quyết được. Tôi cứ nghĩ là số tiền nhỏ thôi nhưng nhận được 950.000 won thì cảm thấy rất tuyệt! Thật may mắn khi có dịch vụ như thế này dành cho người nước ngoài. Mọi người hãy tìm lại quyền lợi của mình nhé.",
  "함께하는 동료들의 리얼 후기": "Đánh giá chân thực từ đồng nghiệp",
};
